language: node_js
node_js:
  - 11.9.0
before_script: 
  - cd backend
  - npm install -g eslint
  - npm install
script:
  - "npm run lint"
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: b6ba4d43-8063-4e53-bef7-db86a17d62dd
  app: labellab-mobile
  on:
    repo: UdeshUK/LabelLab